%__________________________________________________________________________
%
% REEFMOD COUNTERFACTUAL RESULTS 2024
%
% Yves-Marie Bozec, y.bozec@uq.edu.au, 06/2024
%__________________________________________________________________________

clear
SaveDir = '';

SETTINGS_PLOTS % general settings for plotting

% Pick the SSP
ssp = 3 % only SSP2-4.5 available

% Concatenate all gcm runs
X = nan(93,213,1); % primer: 93 years (2007-2099), 213 sites

if ssp == 1
    gcm_list = [1:5 7 9];
else
    gcm_list = [1:10];
end

for gcm = gcm_list

    % Load the raw C~scape output files iteratively for SSP2-4.5 (one file for each of the 10 GCMs)
    % Each file contains all coral outputs per site (213 sites) across the Moore reef cluster
    % There are 10 files (792 MB in total) available upon request
    load(['Moore_SSP' All_SSPs{ssp} '_' All_GCMs{gcm} '.mat'])
    % Coral trajectory per species for 5 taxonomic groups (ignoring staghorn Acropora) for 213 habitat sites in the Moore reef cluster
    % for a given GCM. Coral cover listed per year then per coral group, then per site_id then per run_id
    nb_years = max(CSCAPE.year)-min(CSCAPE.year)+1;
    nb_sp = max(CSCAPE.sp)-min(CSCAPE.sp)+1;
    nb_sites = max(CSCAPE.site_id)-min(CSCAPE.site_id)+1;
    nb_runs = max(CSCAPE.run_id)-min(CSCAPE.run_id)+1;

    C = reshape(CSCAPE.coral_cover_mean_reef,nb_years,nb_sp,nb_sites,nb_runs);
    % For some reason start year is 2007, last is 2099 so need to shift one year forward

    C_tot = squeeze(sum(C,2)); % sum across the 5 taxonomic groups

    X = cat(3,X,C_tot);
end

X = X(:,:,2:end); %remove the primer

% Now sample the run following the list of run ID generated by bootstrap
load('GBR.7.0_likely_runs_NEW.mat') % gives the IDs of runs sampled by bootstrap

X_lik = nan(93,213,1); % primer
select  = LIKELY_RUNS(ssp).select; % list of sampled run IDs
N = 100; % number of bootstrap samples

for n = 1:N % for every bootstrap sample
    X_lik = cat(3,X_lik, X(:,:,select(:,n)));
end

X_lik = X_lik(:,:,2:end); %remove the primer

%% Calculate mean coral cover across 100 bootstrap weighted by likelihood of GCM
Mean_CC_lik = mean(X_lik,3);
YEARS = 2007:1:2099;

% Mapping parameters
FontSizeTowns = 11 ;
FontSizeCoord = 14 ;
FontSizeTitleCC = 12 ; % for some reason needs to be downsized when printed

YearLabRange = {'2030-2040' ; '2050-2060' ; '2070-2080' ; '2090-2100'};
All_years = [ 2035 2055 2075 2095 ];

MyMap = shaperead('MooreShapefile.shp','UseGeoCoords', true);

MyPalette = colormap(brewermap([],'RdYlGn'));

RANGE = 0:10:40 ; RANGE_lab = {' 0';'10';'20';'30';'40'} ;

for decade = 1:length(All_years)

    select_year = All_years(decade);
    I = find(YEARS > select_year-5 & YEARS <= select_year+5);
    Y = squeeze(nanmean(X_lik(I,:,:),3));
    Z = nanmean(Y,1);

    COLS_CC = ceil(size(MyPalette,1)*Z/max(RANGE));
    COLS_CC(COLS_CC>size(MyPalette,1))=size(MyPalette,1);
    faceColors = makesymbolspec('Polygon',{'INDEX',[1 numel(MyMap)],'FaceColor',MyPalette(COLS_CC,:)});

    hfig = figure('visible','on');
    width=400; height=600; set(hfig,'color','w','units','points','position',[0,0,width,height])
    set(gca,'Layer', 'top','FontName', 'Arial' , 'FontSize', 8, 'color',rgb('LightBlue')); set(gcf, 'InvertHardcopy', 'off');
    hold on
    for lat = -16.7:-0.02:-17 ; line([146 146.5],[lat lat],'LineStyle','-','LineWidth',0.05,'Color',0.3*[1 1 1]); end
    for lon = 146:0.02:146.5 ; line([lon lon],[-17 -16.76],'LineStyle','-','LineWidth',0.05,'Color',0.3*[1 1 1]); end
    box on
    hold on
    geoshow(MyMap,'DisplayType','polygon','SymbolSpec',faceColors,'LineWidth',0.01,'EdgeColor',0*[1 1 1])

    % Set-up axes
    AxisLimits = [146.155 146.325 -16.945 -16.775];
    axis equal
    axis(AxisLimits);

    xticks([146.1:0.1:146.4])
    yticks([-17:0.1:-16.7])

    savefig(hfig,[SaveDir '/Maps/MAP_Cscape_Lik_SSP_' All_SSPs{ssp} '_DECADE' num2str(decade)])
    close all
end
