%__________________________________________________________________________
%
% REEFMOD COUNTERFACTUAL CONSTRUCTIONAL STATE (DISTRIS)
%
% Yves-Marie Bozec, y.bozec@uq.edu.au, 07/2023
%__________________________________________________________________________
clear
SaveDir = 'FIGS/Raw_figs/'

load('GBR.7.0_averages_DHW8.mat')
% load('GBR.7.0_likely_runs.mat') % gives the IDs of runs sampled by bootstrap
% load('GBR.7.0_likely_runs_NEW.mat'); boot_select = '_BOOT100_SSP'; % gives the IDs of runs sampled by bootstrap (N=100)
load('GBR.7.0_likely_runs_NEW2.mat'); boot_select = '_BOOT1000_SSP';  % gives the IDs of runs sampled by bootstrap (N=1000)

SETTINGS_PLOTS

N = size(LIKELY_RUNS(1).select,2); % number of bootstrap samples

for ssp = 1:5

    if ssp == 1
        gcm_list = [1:5 7 9];
    else
        gcm_list = [1:10];
    end

    % Concatenate all gcm runs
    X = nan(1,94); % primer
    for gcm = gcm_list
        % X = [X ; all_models(ssp,gcm).C_tot(:,1:end)];OutputName = 'CC_TOT'; maxY = 56; stepY = 10; Ylab = 'Mean coral cover (%)';
        % X = [X ; sum(all_models(ssp,gcm).C_taxa(:,1:end,1:4),3)]; OutputName = 'CC_SENSIT'; maxY = 42; stepY = 10; Ylab = 'Mean coral cover (%)';
        % X = [X ; sum(all_models(ssp,gcm).C_taxa(:,1:end,5:6),3)]; OutputName = 'CC_RESIST'; maxY = 42; stepY = 10;  Ylab = 'Mean coral cover (%)';
        % X = [X ; nanmean(all_models(ssp,gcm).C_taxa_HT_mean(:,1:end,1:4),3)]; OutputName = 'HT_SENSIT'; maxY = 7.6; stepY = 1; Ylab = 'Mean HT (°C-week)';
        % X = [X ; nanmean(all_models(ssp,gcm).C_taxa_HT_mean(:,1:end,5:6),3)]; OutputName = 'HT_RESIST'; maxY = 7.6; stepY = 1; Ylab = 'Mean HT (°C-week)';
        % X = [X ; (all_models(ssp,gcm).nb_coral_juv(:,1:end)+all_models(ssp,gcm).nb_coral_recruit(:,1:end))/400]; OutputName = 'NB_JUV'; maxY = 11.7; stepY = 2; Ylab = 'Mean number of juveniles (m^{-2})';
        % X = [X ; all_models(ssp,gcm).nb_healthy_reefs(:,1:end)*100/3806]; OutputName = 'PROP_H20_REEFS'; maxY = 100; stepY = 10; Ylab = 'Healthy reef habitats (%)';
        % X = [X ; 100-all_models(ssp,gcm).nb_healthy_reefs(:,1:end)*100/3806]; OutputName = 'PROP_UNH20_REEFS'; maxY = 100; stepY = 20; Ylab = 'Unhealthy reef habitats (%)';
        X = [X ; all_models(ssp,gcm).nb_unhealthy_reefs(:,1:end)*100/3806]; OutputName = 'PROP_UNH05_REEFS'; maxY = 100; stepY = 20; Ylab = 'Unhealthy reef habitats (%)';
    end

    X = X(2:end,:); % remove te primer

    % Now sample the run following the list of run ID generated by bootstrap
    X_lik = nan(1,94); % primer
    select  = LIKELY_RUNS(ssp).select; % list of sampled run IDs

    for n = 1:N % for every bootstrap sample
        X_lik = [X_lik ; X(select(:,n),:)];
    end

    X_lik = X_lik(2:end,:); % remove the primer

    % Combine values by 2-year intervals
    % Y = [X_lik(:,1:2:end) ; X_lik(:,2:2:end)]; % to get a biennal distri
    Y = [X_lik(:,2:2:end)]; % to get a biennal distri starting in 2008 ending 2100

    % Format list of years accordingly
    Z = repmat(2008:2:2100,size(Y,1),1);

    %% Plot distributions of GBR mean total cover
    hfig = figure;
    set(gca,'color',rgb('PaleTurquoise'),'Layer', 'top')
    set(gca, 'FontName', 'Arial' ,'FontSize',myGraphicParms.FontSizeLabelTicks);

    Y_select = reshape(Y, size(Y,1)*size(Y,2), 1);
    Z_select = single(reshape(Z, size(Z,1)*size(Z,2), 1));

    I = ismember(Z_select, 2008:2:2100); % spot the selected years

    hold on
    hb = boxplot(Y_select(I==1),Z_select(I==1),'Plotstyle','compact','Color',rgb(All_SSP_colours(ssp)),'symbol','');

    % Record outliers
    hOutliers = findobj(hb,'Tag','Outliers');
    yy = get(hOutliers,'YData');
    NbOutliers = zeros(size(yy));
    for l = 1:length(NbOutliers)
        if isnan(yy{l,1}) == 1
            NbOutliers(l) = 0 ;
        else
            NbOutliers(l) = length(yy{l,1}) ; % NaN will be recorded as 1, while in fact there is no outlier
        end
    end
    disp(['Total number of boxplots: ' num2str(length(NbOutliers))])
    disp(['Number of boxplots without outliers: ' num2str(length(find(NbOutliers==0)))])
    disp(['Maximum number of outliers (as % of points): ' num2str(100*max(NbOutliers)/size(Y,1))])
    disp(['Mean number of outliers (as % of points): ' num2str(100*mean(NbOutliers)/size(Y,1))])

    hICR = findobj(hb,'Tag','Box'); zz = get(hICR,'YData');
    hMedianOuter = findobj(hb,'Tag','MedianOuter'); zz_mo = get(hMedianOuter,'YData');
    % hMedianInner = findobj(hb,'Tag','MedianInner'); zz_mi = get(hMedianInner,'YData');

    % Store all results
    SUMMARY(ssp).Y = Y;
    SUMMARY(ssp).stat_descriptors = {'Year';'25th pctile';'75th pctile';'median';'nb of outliers'};
    SUMMARY(ssp).stats = [[2008:2:2100]' cell2mat(zz) cell2mat(zz_mo) NbOutliers];

    set(gca,'XTickLabel',{' '})
    axis([7 48 0 maxY]) % 8 start in 2022

    set(gca,'Layer', 'top','FontName', 'Arial' ,'FontSize',myGraphicParms.FontSizeLabelTicks);
    yticks([0:stepY:maxY])
    ylabel({Ylab;''},'FontName', 'Arial', 'FontWeight','normal','FontSize',myGraphicParms.FontSizeLabelAxes)

    xticks([12:10:50])
    xticklabels({'2030','2050','2070','2090'})

    T1 = title(All_SSP_names(ssp),'Units','normalized','FontName', 'Arial','FontWeight','bold','FontSize',14);
    T1.Color = rgb(All_SSP_colours(ssp));

    savefig(hfig,[SaveDir 'GBR.7.0_DHW8_Likely_Distri_GBR_Mean_' OutputName boot_select All_SSPs{ssp} '.fig'])

    close all

end

save(['STAT_LIKDISTRI_' OutputName], 'SUMMARY')


%% DETAILED ASSESSMENT
SETTINGS_PLOTS

%% MEAN CORAL COVER ALL IN ONE PLOT
load('STAT_LIKDISTRI_CC_TOT.mat')

% Detailed assessment: 
% Collate the yearly medians (col 4 in stats) of each ssp for plotting
TMP = [SUMMARY(1).stats(:,[1 4]) SUMMARY(2).stats(:,4) SUMMARY(3).stats(:,4) SUMMARY(4).stats(:,4) SUMMARY(5).stats(:,4)];
ALL_Y = [];

figure; 
for i=1:5
    plot([2008:2:2100],TMP(:,(i+1):end),'Color',rgb(All_SSP_colours{i}),'LineWidth',1.5)
    hold on
    ALL_Y = [ALL_Y ; SUMMARY(i).Y];
end

%% Median and ICR in 2024 and 2040 (across all SSPs)
select_year = [9 17]; % column 8 is 2022, 9 is 2024, 17 is 2040, 22 is 2050, 47 is 2100
CC_median = median(ALL_Y(:,select_year))
CC_25th = prctile(ALL_Y(:,select_year),25)
CC_75th = prctile(ALL_Y(:,select_year),75)

%% Mean in 2024 and 2040 (across all SSPs)
select_year = [9 17]; % column 8 is 2022, 9 is 2024, 17 is 2040, 22 is 2050, 47 is 2100

disp('average GBR mean in 2024 and 2040')
MEAN_GBR_mean = mean(ALL_Y(:,select_year))
SD_GBR_mean = std(ALL_Y(:,select_year),1);

disp('95% prediction interval of the GBR mean')
PI1_GBR_mean = MEAN_GBR_mean - 1.96*sqrt(SD_GBR_mean.^2 + (SD_GBR_mean.^2)/size(ALL_Y,1))
PI2_GBR_mean = MEAN_GBR_mean + 1.96*sqrt(SD_GBR_mean.^2 + (SD_GBR_mean.^2)/size(ALL_Y,1))

%% Mean under SSP2-4.5 in 2050 and 2100
select_year = [22 47]; % column 22 is 2050, 47 is 2100

disp('average GBR mean in 2050 and 2100')
MEAN_GBR_mean_SSP245 = mean(SUMMARY(3).Y(:,select_year),1)
SD_GBR_mean_SSP245 = std(SUMMARY(3).Y(:,select_year),1);

disp('95% prediction interval of the GBR mean')
PI1_GBR_mean_SSP245 = MEAN_GBR_mean_SSP245 - 1.96*sqrt(SD_GBR_mean_SSP245.^2 + (SD_GBR_mean_SSP245.^2)/size(SUMMARY(3).Y(:,select_year),1))
PI2_GBR_mean_SSP245 = MEAN_GBR_mean_SSP245 + 1.96*sqrt(SD_GBR_mean_SSP245.^2 + (SD_GBR_mean_SSP245.^2)/size(SUMMARY(3).Y(:,select_year),1))

%% Median and ICR under SSP2-4.5 in 2050 and 2100
select_year = [22 47]; % column 22 is 2050, 47 is 2100
CC_median = median(SUMMARY(3).Y(:,select_year))
CC_25th = prctile(SUMMARY(3).Y(:,select_year),25)
CC_75th = prctile(SUMMARY(3).Y(:,select_year),75)

%% Median in 2024 for each SSP
median(SUMMARY(1).Y(:,9))
median(SUMMARY(2).Y(:,9))
median(SUMMARY(3).Y(:,9))
median(SUMMARY(4).Y(:,9))
median(SUMMARY(5).Y(:,9))

%% 2) UNHEALTHY REEFS
load('STAT_LIKDISTRI_PROP_UNH05_REEFS.mat')
select_year = [22 47]; % column 22 is 2050, 47 is 2100

disp('average number of reefs under 5% coral cover in 2050 and 2100')
MEAN_GBR_unhealthy_reefs_SSP245 = mean(SUMMARY(3).Y(:,select_year),1)
SD_GBR_unhealthy_reefs_SSP245 = std(SUMMARY(3).Y(:,select_year),1);

disp('95% prediction interval of the GBR mean')
PI1_GBR_mean_SSP245 = MEAN_GBR_unhealthy_reefs_SSP245 - 1.96*sqrt(SD_GBR_unhealthy_reefs_SSP245.^2 + (SD_GBR_unhealthy_reefs_SSP245.^2)/size(SUMMARY(3).Y(:,select_year),1))
PI2_GBR_mean_SSP245 = MEAN_GBR_unhealthy_reefs_SSP245 + 1.96*sqrt(SD_GBR_unhealthy_reefs_SSP245.^2 + (SD_GBR_unhealthy_reefs_SSP245.^2)/size(SUMMARY(3).Y(:,select_year),1))
